version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
  service:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: docker
    directory: /
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: docker
    directory: /monitoring
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: gomod
    directory: /
    multi-ecosystem-group: "service"
    
  - package-ecosystem: npm
    directory: /
    multi-ecosystem-group: "service"

  - package-ecosystem: npm
    directory: /test/util
    multi-ecosystem-group: "service"

  - package-ecosystem: npm
    directory: /typescript/cli
    multi-ecosystem-group: "service"

  - package-ecosystem: npm
    directory: /typescript/config
    multi-ecosystem-group: "service"
